package org.motechproject.whp.mtraining.dto;

import java.util.List;
import java.util.UUID;

/**
 * Contract object representing a Question.
 * Message
 *   + name    : Question name
 *   + description : Question description
 *   + contentId   : UUID that for a question (different from the _id generated by couch)
 *   + version     : question version (a quiz can have multiple versions, different versions of the question will have same contentId)
 *   + externalContentId  : Id that points to an external file or resource that is associated with the question.For eg. an audio file that is played to the enrollee
 *   + createdBy    : Author of the question
 *   + createdOn    : Date on which question was created
 *   + answer       : correct option for the question
 *   +options       : options to be played out for this question
 */
public class QuestionDto extends ContentDto {
    private String name;
    private String description;
    private AnswerDto answer;
    private List<String> options;

    public QuestionDto() {
    }

    public QuestionDto(boolean isActive, String name, String description, String externalId, AnswerDto answer, List<String> options, String createdBy) {
        super(isActive, externalId, createdBy);
        this.name = name;
        this.description = description;
        this.answer = answer;
        this.options = options;
    }

    public QuestionDto(UUID contentId, Integer version, boolean isActive, String name, String description, String externalId, AnswerDto answer, List<String> options, String createdBy) {
        super(contentId, version, isActive, externalId, createdBy);
        this.name = name;
        this.description = description;
        this.answer = answer;
        this.options = options;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public AnswerDto getAnswer() {
        return answer;
    }

    public List<String> getOptions() {
        return options;
    }
}
