package org.motechproject.whp.mtraining.dto;

import java.util.List;
import java.util.UUID;

/**
 * Contract object representing a Quiz content.
 *   + name    : quiz name
 *   + contentId   : UUID that for a quiz (different from the _id generated by couch)
 *   + version     : quiz version (a quiz can have multiple versions, different versions of the quiz will have same contentId)
 *   + externalContentId  : Id that points to an external file or resource that is associated with the quiz.For eg. an audio file that is played to the enrollee
 *   + createdBy    : Author of the quiz
 *   + createdOn    : Date on which quiz was created
 *   + passPercentage : Pass percentage for the quiz
 *   + strategy       : strategy for selecting quiz questions.
 *   + numberOfQuizQuestionsToBePlayed : Number of quiz questions to be played to the enrollee taking the quiz. Its value will be lesser than or equal to total number of questions available in the quiz.
 */
public class QuizDto extends ContentDto {
    private String name;
    private List<QuestionDto> questions;
    private Integer noOfQuestionsToBePlayed;
    private Double passPercentage;

    public QuizDto() {
    }

    public QuizDto(boolean isActive, String name, String externalId, List<QuestionDto> questions, Integer noOfQuestionsToBePlayed, Double passPercentage, String createdBy) {
        super(isActive, externalId, createdBy);
        this.name = name;
        this.questions = questions;
        this.noOfQuestionsToBePlayed = noOfQuestionsToBePlayed;
        this.passPercentage = passPercentage;
    }

    public QuizDto(UUID contentId, Integer version, boolean isActive, String name, String externalId, List<QuestionDto> questions, Integer noOfQuestionsToBePlayed, Double passPercentage, String createdBy) {
        super(contentId, version, isActive, externalId, createdBy);
        this.name = name;
        this.questions = questions;
        this.noOfQuestionsToBePlayed = noOfQuestionsToBePlayed;
        this.passPercentage = passPercentage;
    }

    public String getName() {
        return name;
    }

    public List<QuestionDto> getQuestions() {
        return questions;
    }

    public Integer getNoOfQuestionsToBePlayed() {
        return noOfQuestionsToBePlayed;
    }

    public Double getPassPercentage() {
        return passPercentage;
    }
}
